### ISSUE TITLE
Catkinze package

### ISSUE THREAD

**Issue by k-okada** [start-jsk/open_industrial_ros_controllers#1]
Catkinze package for release

**Comment by k-okada** [comment]
catkinize しました．
https://github.com/start-jsk/open-industrial-ros-controllers/commit/361151c0d35d8fd025eb40f15f6a7f8919223bf2
で，hydroのみになってしまっていますが，必要ならgroovyにもできるようにします

とりあえず，一旦クローズで

**Comment by 130s** [comment]
確認ですが，`densowave` には catkinize されてない package が幾つかあるようですが，それらはリリースする必要が無いということでしょうか？

```
/open-industrial-ros-controllers/densowave$ find . -iname 'package.xml'
./vs060/package.xml
./denso_controller/package.xml
./densowave/package.xml
./vs060_moveit_config/package.xml
./denso_launch/package.xml

/open-industrial-ros-controllers/densowave$ find . -iname 'manifest.xml'
./denso_pendant_publisher/manifest.xml
./vs060/manifest.xml
./denso_controller/manifest.xml
./vs060A1_AV6_NNN_NNN_arm_navigation/manifest.xml
./denso_irex_ui/manifest.xml
./denso_launch/manifest.xml
```

もしそうでなくて単に漏れているだけであればこちらで catkinize しておきます．

あと，`rosbuild` 対応の可能性は残っているか分かりませんが，`manifest.xml` は消さないでおきます．

**Comment by k-okada** [comment]
はい。とりあえずシミュレーションに必要なものだけを catkinze しました。
ユーザーが出てくるまでこれでいいとおもいます

**Comment by 130s** [comment]
承知です．
