### ISSUE TITLE
Clarify advantage (and future plan if any) 

### ISSUE THREAD

**Issue by 130s** [start-jsk/open_industrial_ros_controllers#12]
With a few other similar existing packages, it will be confusing to ROS users without being documented. I've started to mention the advantage and imply the future plan. Please review and correct. @k-okada 
http://wiki.ros.org/open_industrial_ros_controllers#Relationship_to_existing_contoller_components

**Comment by k-okada** [comment]
My plan is to integrate open_industrial_ros_control into [ros_control](http://wiki.ros.org/ros_control/) and we will provide driver (`bCap`) level.
One thing we're not sure is that how `ros_control` keeps periodic cycle, in `open_industroal_ros_control`, we first used `pthread` timer to run main loop at 4msec, but at the end, we wait until `RC-8` send packet, and execute next loop, so RC-8 triggers the periodic main loop of the controller. We're not sure if ros_control support this type of execution model, and if not we'd improve ros_control.
