### ISSUE TITLE
Release package

### ISSUE THREAD

**Issue by k-okada** [start-jsk/open_industrial_ros_controllers#2]
This depends on #1

**Comment by k-okada** [comment]
#1 　ができたので，リリースをお願いできますか→　 @130s さん．
 roslaunch  vs060_moveit_config demo_simulation.launch 
でとりあえず，moveitの画面が上がるので，ここまでできたら，またros-usersに連絡しましょう．

**Comment by 130s** [comment]
承知しました．

[package 名の件](https://github.com/start-jsk/open-industrial-ros-controllers/issues/3)，どうでしょう？

**Comment by 130s** [comment]
確認ですが，これ，Hydro 限定ですよね？

G だと `pr2_controllers` は dry のようです．

**Comment by k-okada** [comment]
はい
そうなります。

**Comment by 130s** [comment]
Although not yet done, I've made `hydro-devel` branch via a3464af95d593b8ae52e68c3f3ecc7e40132161a, in case there will be a need for `Groovy` or downward version. There I've also removed `web_interface` package that's already planned to be moved somewhere else.

**Comment by 130s** [comment]
http://www.ros.org/debbuild/hydro.html?q=open_ 
なぜか `Precise 64b` だけ失敗しているが (何かのきっかけでたまたま失敗したのだと期待) それ以外は `shadow-fixed` にビルド済．要 runtime test.

**Comment by 130s** [comment]
`Precise 64b` も build されたので do #9.
