### ISSUE TITLE
Consider renaming VS060A1_AV6_NNN_NNN_arm_navigation pkg

### ISSUE THREAD

**Issue by 130s** [start-jsk/open_industrial_ros_controllers#4]
capital で始まる package があると，`catkin_make` など幾つかの ROS ツールが大量の `warning` を吐くので，output がとても読みにくいです．

`vs060A1_AV6_NNN_NNN_arm_navigation` とかに変えて問題なければこちらでやります．

**Comment by garaemon** [comment]
おねがいします

-- ryohei

**Comment by 130s** [comment]
Done in 3e68c1ee3093c58702cfa21d3d268ee29097ae9d (`hydro-devel` only).
