### ISSUE TITLE
Catkinize open_industrial_web_interface

### ISSUE THREAD

**Issue by 130s** [start-jsk/open_industrial_ros_controllers#5]
私がやります．

結局，依存してる package 達も catkinize することになる気がしています．その場合それらも `open-industrial-ros-controllers` に取り込んで構わないでしょうか？例えば以下のように `open_industrial_web` とかいう metapackage を作ることになるかと．

```
open-industrial-ros-controllers
|-open_industrial_web (metapkg)
   |- open_industrial_web_interface  (@KazutoMurase 作成の package)
   |- depended_pkg_a
   |- depended_pkg_b
   :
```

**Comment by garaemon** [comment]
はい、良いと思います

**Comment by k-okada** [comment]
名前と置き場所は，open_industrial_web　ではなくて，
https://github.com/tork-a/visualization_rwt
とか，
https://github.com/tork-a/rwt_apps
においたらいいというアイデアがでていました． @KazutoMurase 君が考えているはずです．

**Comment by 130s** [comment]
確認ですが，`open_industrial_web_interface` は `open-industrial-ros-controllers` に含まれなくする，ということでしょうか？

あと，これは知りたかったことですが，`open_industrial_web_interface` はどの辺が "industrial" と付くべきになっていますか？

**Comment by k-okada** [comment]
> あと，これは知りたかったことですが，open_industrial_web_interface はどの辺が "industrial" と付くべきになっていますか？

industrialと着くべきところがないので，open-industrial-ros-controllersから外して良いのでは，と思っています．

**Comment by 130s** [comment]
なるほど．では @KazutoMurase，然るべき所に移動したら連絡下さい．

**Comment by KazutoMurase** [comment]
@130s さん @k-okada  先生
了解しました。
