### ISSUE TITLE
Move open_industrial_web_interface to appropriate repository

### ISSUE THREAD

**Issue by 130s** [start-jsk/open_industrial_ros_controllers#6]
#5 より派生．

**Comment by 130s** [comment]
Btw `roswww` is now available from `apt-get`. 
http://www.ros.org/debbuild/hydro.html?q=www

**Comment by KazutoMurase** [comment]
rwt_apps以下にrwt_moveitを作成しました.
とりあえずdevelopブランチにしてあります.
makeして、vs060とpr2のsim環境で動くところまで確認しました.

**Comment by 130s** [comment]
ありがとうございます！
