### ISSUE TITLE
Why open_industrial_web_interface use a deprecated package roswww?

### ISSUE THREAD

**Issue by 130s** [start-jsk/open_industrial_ros_controllers#7]
@KazutoMurase [roswww は deprecated](http://answers.ros.org/question/62324/what-is-roswww-and-how-does-it-relate-to-rosbridge/) のようですね．`rosbridge_*` を使うのだとまずいですか？

見たところ [rosbridge_server/src/tornado](https://github.com/RobotWebTools/rosbridge_suite/tree/hydro-devel/rosbridge_server/src/tornado) と [roswww/src/tornado](https://github.com/tork-a/roswww_pkg/tree/groovy-devel/roswww/src/tornado) はほぼ同じように見えていて，`roswww` にしかないのは実行可能な `webserver.py` というスクリプトだけ？

[roswww を fork して](https://github.com/tork-a/roswww_pkg) Groovy にリリースしたところ，.deb のインストール時に `rosbridge` と被るという `dpkg` のエラーが出て，以後の apt-get が進まなくなります．可能なかぎりよくメンテされている `rosbridge` を使うべきと思います (もしそう変更できたら，`tork-a/roswww` は削除します)．

```
Unpacking ros-groovy-roswww (from .../ros-groovy-roswww_0.1.1-0precise-20131115-1453-+0000_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/ros-groovy-roswww_0.1.1-0precise-20131115-1453-+0000_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/groovy/lib/python2.7/dist-packages/tornado/httpserver.pyc', which is also in package ros-groovy-rosbridge-server 0.4.4-0precise-20131016-0330-+0000
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ros-groovy-roswww_0.1.1-0precise-20131115-1453-+0000_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by 130s** [comment]
@KazutoMurase こちらも教えてくれるとありがたいです．[こういう問題](https://github.com/tork-a/roswww_pkg/issues/1)が起こってるので早めに解決したいところでして．

**Comment by KazutoMurase** [comment]
@130s さん
その削除された`webserver.py`を正に使用しております.
ただこのスクリプトはrosの全packageのwwwディレクトリ以下を、何も考えずwebページにするだけのスクリプトで、もう少しapacheみたく色々な機能があると(アクセス制限など)いいよね、という話を植田さんとしておりました。
その改良のための`tork-a/roswww`(名前はros-web-serverもしくはrwt_serverなど？)という理解です.
webserver.py自体にbridge機能は無いので、外されたのだと思います.

**Comment by KazutoMurase** [comment]
よって現状`rosbridge_*`に変更は不可能で、かつwebserver.pyをこちらに含めるという流れも無いと思います。

**Comment by KazutoMurase** [comment]
とりあえず、現状はpackageにするレベルでも無いのであれば、
rwt_moveitにwebserver.pyを含めておいて、
中身を
roslib.load_manifest('roswww') -> roslib.load_manifest('rosbridge_server')
とすれば`rosbridge`への依存のみになりますがいかがでしょうか？

**Comment by 130s** [comment]
ほほう，ということは，

`rwt_moveit` 等 `rwt_apps` をとりあえず動作させるためには，`tork-a/roswww` は `rosbridge` に依存しつつ `webserver.py` だけ持っておくようにすれば良いですかね？

上記で良ければ以下の部分は今後の追加開発ということで良くなりますよね．

> webserver.py
> ただこのスクリプトはrosの全packageのwwwディレクトリ以下を、何も考えずwebページにするだけのスクリプトで、もう少しapacheみたく色々な機能があると(アクセス制限など)いいよね、という話を植田さんとしておりました。

**Comment by 130s** [comment]
投稿タイミングかぶった :)

なるほど．じゃあ，`rwt_common` みたいな pkg を `rwt_apps` (か，より適正な場所があったら教えて下さい) に `webserver.py` を入れて置くという手はあるね．

ただ，webserver だけを使いたい人が `rwt_apps` に依存するのも冗長だし，`tork-a/roswww` 既にリリースしてしまってるという便宜もあるから，`tork-a/roswww` に入れて置くのでどうでしょうか．

**Comment by KazutoMurase** [comment]
@130s さん
そうですね. 現状はそれで良いと思います.
ちなみに先程のload_manifestの行のみの変更で、動作する事は確認しました.
宜しくおねがいします.

**Comment by 130s** [comment]
了解です．ちなみに `rwt_apps` とか一連の web 関連って ROS の distro は？ Catkin only? Groovy+rosmake も想定内？

**Comment by KazutoMurase** [comment]
Groovy+rosmake も想定内で良いと思います.
